---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/ceph-daemon
  matrix:
    - VERSION=v3.1.0-stable-3.1-luminous
    - VERSION=v3.2.1-stable-3.2-luminous
    - VERSION=v3.2.7-stable-3.2-luminous
    - VERSION=v3.2.8-stable-3.2-luminous
    - VERSION=v4.0.4-stable-4.0-nautilus
    - VERSION=v4.0.5-stable-4.0-nautilus
    - VERSION=v4.0.6-stable-4.0-nautilus

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
